[target.s390x-unknown-linux-gnu]
image = "ghcr.io/cross-rs/s390x-unknown-linux-gnu:main"
pre-build = [
  "apt-get update && apt-get --assume-yes --no-install-recommends install libclang-12-dev clang-12 llvm-12-dev valgrind",
]

[target.i686-unknown-linux-gnu]
image = "ghcr.io/cross-rs/i686-unknown-linux-gnu:main"
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update && apt-get --assume-yes --no-install-recommends install valgrind:$CROSS_DEB_ARCH",
]
