[package]
name = "benchmark-tests"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["Joining7943 <joining@posteo.de>"]
rust-version = "1.60.0"
description = "Tests for iai-callgrind"
readme = "../README.md"
homepage = "https://github.com/iai-callgrind/iai-callgrind"
repository = "https://github.com/iai-callgrind/iai-callgrind"
license = "Apache-2.0 OR MIT"

[dependencies]
cargo_metadata = { version = "0.17" }
colored = { version = ">=1.6, <3" }
glob = { version = "0.3" }
iai-callgrind = { path = "../iai-callgrind", features = [
  "client_requests_defs",
] }
iai-callgrind-runner = { path = "../iai-callgrind-runner" }
new_string_template = { version = "1.4" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
valico = { version = "4" }

[[bin]]
name = "benchmark-tests-printenv"
path = "src/benchmark-tests-printenv.rs"

[[bin]]
name = "benchmark-tests-cat"
path = "src/benchmark-tests-cat.rs"

[[bin]]
name = "benchmark-tests-exit"
path = "src/benchmark-tests-exit.rs"

[[bin]]
name = "benchmark-tests-echo"
path = "src/benchmark-tests-echo.rs"

[[bin]]
name = "benchmark-tests-sort"
path = "src/benchmark-tests-sort.rs"

[[bin]]
name = "benchmark-tests-subprocess"
path = "src/benchmark-tests-subprocess.rs"

[[bin]]
name = "benchmark-tests-printargs"
path = "src/benchmark-tests-printargs.rs"

[[bin]]
name = "bench"
path = "src/bench.rs"

[[bench]]
name = "test_bin_bench_with_fixtures"
harness = false

[[bench]]
name = "test_bin_bench_with_exit"
harness = false

[[bench]]
name = "test_bin_bench_groups"
harness = false

[[bench]]
name = "test_bin_bench_flamegraph"
harness = false

[[bench]]
name = "test_bin_bench_tools"
harness = false

[[bench]]
name = "test_bin_bench_readme_example"
harness = false

[[bench]]
name = "test_lib_bench_flamegraph"
harness = false

[[bench]]
name = "test_lib_bench_groups"
harness = false

[[bench]]
name = "test_lib_bench_groups_envs"
harness = false

[[bench]]
name = "test_lib_bench_readme_example_fibonacci"
harness = false

[[bench]]
name = "test_lib_bench_tools"
harness = false
