[package]
name = "benchmark-tests"
authors = ["Joining7943 <joining@posteo.de>"]
categories.workspace = true
description = "Tests for iai-callgrind"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
publish = false
readme = "../README.md"
repository.workspace = true
rust-version.workspace = true
version = "0.1.0"

[dependencies]
cargo_metadata = { workspace = true }
colored = { workspace = true }
glob = { workspace = true }
iai-callgrind = { path = "../iai-callgrind", features = [
  "client_requests_defs",
] }
iai-callgrind-runner = { path = "../iai-callgrind-runner" }
lazy_static = { workspace = true }
minijinja = { workspace = true }
once_cell = { workspace = true }
pretty_assertions = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
valico = { workspace = true }

[[bin]]
name = "benchmark-tests-printenv"
path = "src/benchmark-tests-printenv.rs"

[[bin]]
name = "benchmark-tests-cat"
path = "src/benchmark-tests-cat.rs"

[[bin]]
name = "benchmark-tests-exit"
path = "src/benchmark-tests-exit.rs"

[[bin]]
name = "benchmark-tests-echo"
path = "src/benchmark-tests-echo.rs"

[[bin]]
name = "benchmark-tests-sort"
path = "src/benchmark-tests-sort.rs"

[[bin]]
name = "benchmark-tests-subprocess"
path = "src/benchmark-tests-subprocess.rs"

[[bin]]
name = "benchmark-tests-printargs"
path = "src/benchmark-tests-printargs.rs"

[[bin]]
name = "bench"
path = "src/bench.rs"

[[bench]]
name = "test_bin_bench_with_fixtures"
harness = false

[[bench]]
name = "test_bin_bench_with_exit"
harness = false

[[bench]]
name = "test_bin_bench_groups"
harness = false

[[bench]]
name = "test_bin_bench_flamegraph"
harness = false

[[bench]]
name = "test_bin_bench_tools"
harness = false

[[bench]]
name = "test_bin_bench_readme_example"
harness = false

[[bench]]
name = "test_lib_bench_flamegraph"
harness = false

[[bench]]
name = "test_lib_bench_groups"
harness = false

[[bench]]
name = "test_lib_bench_groups_envs"
harness = false

[[bench]]
name = "test_lib_bench_readme_example_fibonacci"
harness = false

[[bench]]
name = "test_lib_bench_tools"
harness = false

[[bench]]
name = "test_lib_bench_multi_thread"
harness = false

[[bench]]
name = "test_bench"
harness = false
