[package]
authors = ["Joining7943 <joining@posteo.de>"]
categories.workspace = true
description = "Tests for iai-callgrind"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "benchmark-tests"
publish = false
readme = "../README.md"
repository.workspace = true
rust-version.workspace = true
version = "0.1.0"

[dependencies]
cargo_metadata = { workspace = true }
colored = { workspace = true }
glob = { workspace = true }
iai-callgrind = { path = "../iai-callgrind", features = [
  "client_requests_defs",
] }
iai-callgrind-runner = { path = "../iai-callgrind-runner" }
lazy_static = { workspace = true }
minijinja = { workspace = true }
once_cell = { workspace = true }
pretty_assertions = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
valico = { workspace = true }

[[bin]]
name = "bench"
path = "src/bench.rs"

[[bin]]
name = "benchmark-tests-sort"
path = "src/benchmark-tests-sort.rs"

[[bench]]
harness = false
name = "test_lib_bench_flamegraph"

[[bench]]
harness = false
name = "test_lib_bench_cache_sim"

[[bench]]
harness = false
name = "test_lib_bench_groups"

[[bench]]
harness = false
name = "test_lib_bench_compare"

[[bench]]
harness = false
name = "test_lib_bench_groups_envs"

[[bench]]
harness = false
name = "test_lib_bench_readme_example_fibonacci"

[[bench]]
harness = false
name = "test_lib_bench_tools"

[[bench]]
harness = false
name = "test_lib_bench_setup_and_teardown"

[[bench]]
harness = false
name = "test_lib_bench_nocapture"

[[bench]]
harness = false
name = "test_lib_bench_compiler_optimization"

[[bench]]
harness = false
name = "test_lib_bench_generics"

[[bench]]
harness = false
name = "test_bench"
