[package]
name = "iai-callgrind"
version = "0.6.1"
edition = "2021"
rust-version = "1.60.0"
authors = [
  "Joining7943 <joining@posteo.de>",
  "Brook Heisler <redattack34@gmail.com>",
]
description = "High-precision and consistent benchmarking framework/harness for Rust"
readme = "../README.md"
homepage = "https://github.com/Joining7943/iai-callgrind"
repository = "https://github.com/Joining7943/iai-callgrind"
license = "Apache-2.0 AND MIT"
keywords = ["iai", "benchmark", "callgrind", "valgrind"]
categories = ["development-tools::profiling", "development-tools::testing"]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
serde = { version = "1", features = ["derive"] }
bincode = "1"
iai-callgrind-runner = { path = "../iai-callgrind-runner/", version = "=0.6.1", default-features = false, features = [
  "api",
] }
