[package]
authors = [
  "Joining7943 <joining@posteo.de>",
  "Brook Heisler <redattack34@gmail.com>",
]
categories.workspace = true
description = "High-precision and consistent benchmarking framework/harness for Rust"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "iai-callgrind"
readme = "../README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
benchmark = [
  "dep:bincode",
  "dep:iai-callgrind-macros",
  "dep:iai-callgrind-runner",
]
client_requests = ["client_requests_defs"]
client_requests_defs = [
  "dep:cty",
  "dep:cfg-if",
  "dep:bindgen",
  "dep:cc",
  "dep:regex",
  "dep:version-compare",
  "dep:strum",
]
default = ["benchmark"]
ui_tests = []

[build-dependencies]
bindgen = { workspace = true, optional = true }
cc = { workspace = true, optional = true }
regex = { workspace = true, optional = true }
version-compare = { workspace = true, optional = true }
strum = { workspace = true, optional = true }

[package.metadata.docs.rs]
features = ["client_requests_defs"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bincode = { workspace = true, optional = true }
cfg-if = { workspace = true, optional = true }
cty = { workspace = true, optional = true }
iai-callgrind-macros = { path = "../iai-callgrind-macros/", version = "=0.3.0", optional = true }
iai-callgrind-runner = { path = "../iai-callgrind-runner/", version = "=0.12.1", default-features = false, features = [
  "api",
], optional = true }

[dev-dependencies]
trybuild = { workspace = true }
