[package]
name = "iai-callgrind-runner"
version = "0.6.1"
edition = "2021"
rust-version = "1.60.0"
authors = [
  "Joining7943 <joining@posteo.de>",
  "Brook Heisler <redattack34@gmail.com>",
]
description = "Binary package needed by the iai-callgrind library"
readme = "README.md"
homepage = "https://github.com/Joining7943/iai-callgrind"
repository = "https://github.com/Joining7943/iai-callgrind"
license = "Apache-2.0 AND MIT"
keywords = ["iai", "benchmark", "callgrind", "valgrind"]
categories = ["development-tools::profiling", "development-tools::testing"]

[features]
default = ["runner", "api"]
runner = []
api = []

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
all-features = true

[dependencies]
log = "0.4"
env_logger = "0.10"
colored = "2"
version-compare = "0.1"
sanitize-filename = "0.5"
which = "4"
tempfile = "3"
bincode = "1"
serde = { version = "1", features = ["derive"] }
shlex = { version = "1" }
cargo_metadata = "0.17"

[dev-dependencies]
rstest = "0.18"

[[bin]]
name = "iai-callgrind-runner"
path = "src/main.rs"
test = true
bench = true
