[package]
name = "iai-callgrind-runner"
version = "0.6.1"
edition = "2021"
rust-version = "1.60.0"
authors = [
  "Joining7943 <joining@posteo.de>",
  "Brook Heisler <redattack34@gmail.com>",
]
description = "Binary package needed by the iai-callgrind library"
readme = "README.md"
homepage = "https://github.com/Joining7943/iai-callgrind"
repository = "https://github.com/Joining7943/iai-callgrind"
license = "Apache-2.0 AND MIT"
keywords = ["iai", "benchmark", "callgrind", "valgrind"]
categories = ["development-tools::profiling", "development-tools::testing"]

[features]
default = ["runner", "api"]
runner = [
  "dep:bincode",
  "dep:cargo_metadata",
  "dep:colored",
  "dep:env_logger",
  "dep:log",
  "dep:sanitize-filename",
  "dep:shlex",
  "dep:tempfile",
  "dep:version-compare",
  "dep:which",
]
api = ["dep:serde"]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
all-features = true

[dependencies]
bincode = { version = "1.3.3", optional = true }
cargo_metadata = { version = "0.17.0", optional = true }
colored = { version = ">=1.6, <=2.0.0", optional = true }
env_logger = { version = ">=0.6, <=0.9.3", optional = true }
log = { version = "0.4.19", optional = true }
sanitize-filename = { version = "0.5.0", optional = true }
serde = { version = "1.0.188", features = ["derive"], optional = true }
shlex = { version = "1.1.0", optional = true }
tempfile = { version = ">=3, <=3.6.0", optional = true }
version-compare = { version = "0.1.1", optional = true }
which = { version = "4.4.0", optional = true }

[dev-dependencies]
rstest = "~0.17"

[[bin]]
name = "iai-callgrind-runner"
path = "src/main.rs"
test = true
bench = true
