[package]
name = "iai-callgrind-runner"
version = "0.9.0"
edition = "2021"
rust-version = "1.60.0"
authors = [
  "Joining7943 <joining@posteo.de>",
  "Brook Heisler <redattack34@gmail.com>",
]
description = "Binary package needed by the iai-callgrind library"
readme = "README.md"
homepage = "https://github.com/iai-callgrind/iai-callgrind"
repository = "https://github.com/iai-callgrind/iai-callgrind"
license = "Apache-2.0 OR MIT"
keywords = ["iai", "benchmark", "callgrind", "valgrind"]
categories = ["development-tools::profiling", "development-tools::testing"]

[features]
api = ["dep:serde"]
default = ["runner"]
runner = [
  "api",
  "dep:anyhow",
  "dep:bincode",
  "dep:cargo_metadata",
  "dep:clap",
  "dep:colored",
  "dep:env_logger",
  "dep:glob",
  "dep:indexmap",
  "dep:inferno",
  "dep:log",
  "dep:regex",
  "dep:sanitize-filename",
  "dep:serde",
  "dep:serde_json",
  "dep:shlex",
  "dep:tempfile",
  "dep:version-compare",
  "dep:which",
]
schema = ["default", "dep:schemars"]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
all-features = true

[dependencies]
anyhow = { version = ">=1.0.46, <2", optional = true }
bincode = { version = "1", optional = true }
cargo_metadata = { version = "0.17", optional = true }
clap = { version = ">=3.2.3, <3.2.24", optional = true, features = [
  "derive",
  "env",
] }
colored = { version = ">=1.6, <3", optional = true }
env_logger = { version = ">=0.7, <0.11", optional = true }
glob = { version = "0.3", optional = true }
indexmap = { version = "1.9", optional = true, features = ["serde"] }
inferno = { version = "0.11.10", optional = true, default-features = false, features = [
  'multithreaded',
] }
lazy_static = { version = "1.4.0" }
log = { version = "0.4", optional = true }
regex = { version = "1", optional = true }
sanitize-filename = { version = "0.5", optional = true }
schemars = { version = "0.8.16", features = ["indexmap1"], optional = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
shlex = { version = "1", optional = true }
tempfile = { version = "3", optional = true }
version-compare = { version = "0.1", optional = true }
which = { version = "4", optional = true }

[dev-dependencies]
pretty_assertions = { version = "1.1" }
rstest = ">=0.17, <0.19"
serde_yaml = { version = "0.9" }
serial_test = { version = "2" }
tempfile = { version = "3" }

[[bin]]
name = "iai-callgrind-runner"
path = "src/main.rs"
test = true
bench = true
required-features = ["default"]

[[bin]]
name = "schema-gen"
path = "src/schema_gen.rs"
test = false
bench = false
required-features = ["schema"]
