# spell-checker:ignore taiki rustfmt binstall clippy taplo rustup

name: Build and Check

on:
  push:
    branches: ["main", "cicd", "release", "develop", "[0-9]+-*"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deny:
    name: Check dependencies/ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - checks: advisories
            arguments: --deny warnings
          - checks: bans licenses sources
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          rust-version: "1.60.0" # MSRV
          command: check ${{ matrix.config.arguments }} ${{ matrix.config.checks }}

  minimal_versions:
    name: Check minimal version requirements of dependencies
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - "1.60.0" # MSRV
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: Swatinem/rust-cache@v2.2.0
        with:
          key: ubuntu-latest_${{ matrix.toolchain }}
      - uses: taiki-e/install-action@cargo-hack
      - uses: taiki-e/install-action@cargo-minimal-versions
      - name: Check build with minimal versions
        run: cargo minimal-versions check --workspace --all-targets --ignore-private

  format:
    name: Check format and spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install prettier
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: taiki-e/install-action@cargo-binstall
      - run: cargo binstall --no-confirm --no-symlinks taplo-cli
      - run: cargo fmt --check
      - run: taplo fmt --check --verbose
      - run: npx prettier --check --log-level warn '**/*.json' '**/*.yml'
      - uses: streetsidesoftware/cspell-action@v3
        with:
          incremental_files_only: false
          verbose: true

  base:
    needs: [format]
    name: Build, check and test
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - "1.60.0" # MSRV
          - stable
          - nightly
        include:
          - toolchain: "1.60.0" # MSRV
            ui_tests: --features ui_tests
          - toolchain: stable
            components: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: ${{ matrix.components }}
      - name: Prepare
        if: matrix.toolchain != 'stable'
        run: |
          rustup toolchain install stable --no-self-update --component clippy
      - uses: taiki-e/install-action@cargo-hack
      - uses: Swatinem/rust-cache@v2.2.0
        with:
          key: ubuntu-latest_${{ matrix.toolchain }}
      - name: Install valgrind
        run: sudo apt-get -y update && sudo apt-get -y install valgrind
      - name: Info
        run: |
          set -x
          uname -a
          pwd
          rustup --version
          rustup show
          rustup component list --installed
          valgrind --version
      - name: Build with the feature powerset
        run: cargo hack --feature-powerset --exclude-features ui_tests build
      - name: Lint
        run: cargo +stable clippy --all-features --all-targets -- -D warnings
      - name: Test
        run: |
          set -o pipefail
          cargo test ${{ matrix.ui_tests }} |& tee test.output
      - name: Check test output for ui errors
        if: ${{ matrix.ui_tests && failure() }}
        run: |
          if grep -q '^test ui \.\.\. FAILED$' test.output; then
            TRYBUILD=overwrite cargo test ${{ matrix.ui_tests }} ui
            git diff iai-callgrind/tests/ui
          fi
          exit 1
      - name: Check summary.json schema is up-to-date
        run: |
          cargo run -p iai-callgrind-runner --features schema --bin schema-gen
          npx prettier --write summary.schema.json
          diff summary.schema.json iai-callgrind-runner/schemas/summary.v1.schema.json
      - name: Bench
        run: cargo run --package benchmark-tests --profile=bench --bin bench
        # env:
        # IAI_CALLGRIND_LOG: trace
      - uses: actions/upload-artifact@v3
        with:
          name: iai-callgrind-benchmarks
          path: "target/iai"

  docs:
    needs: [base]
    name: Docs/ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2.2.0
      - name: Run doc tests
        run: cargo test --all-features --doc
      - name: Check Documentation
        run: cargo doc --all-features --no-deps --document-private-items
